### ISSUE TITLE
Rectangular Toeplitz/Hankel Matrices

### ISSUE THREAD

**Issue by kuanxu** [JuliaMatrices/ToeplitzMatrices.jl#11]
1. May I know any reason why fast application of a rectangular Toeplitz/Hankel Matrix has not been implemented? If nobody objects, I'd like to make it work for an n x m Toeplitz/Hankel.

2. Is there any rationale for padding the `tmp` vector with a zero? Making `tmp` to be of even length for a bit gain in FFT speed?
```
tmp = complex([vc; zero(T); reverse(vr[2:end])]) 
```

**Comment by dlfivefifty** [comment]
I think adding support for the rectangular case would be great!

**Comment by andreasnoack** [comment]
Yes. Please go ahead. The implemented methods only reflect what I needed for my PhD thesis.

**Comment by andreasnoack** [comment]
Fixed by #15
