### ISSUE TITLE
Complex input not supported

### ISSUE THREAD

**Issue by kuanxu** [JuliaMatrices/ToeplitzMatrices.jl#16]
Hi all,

It seems that complex input is not supported.
```
Julia> v1 = [1.0+1.0im,2.,3.]
Julia> v2 = [1.0+1.0im,5.0+1.1im,6.]
Julia> A = Toeplitz(v1, v2)
ERROR: LoadError: MethodError: `convert` has no method matching convert(::Type{ToeplitzMatrices.Toeplitz{T<:Number}}, ::Array{Complex{Float64},1}, ::Array{Complex{Float64},1}, ::Array{Complex{Float64},1}, ::Array{Complex{Float64},1}, ::Base.DFT.FFTW.cFFTWPlan{Complex{Float64},-1,true,1})
This may have arisen from a call to the constructor ToeplitzMatrices.Toeplitz{T<:Number}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  ToeplitzMatrices.Toeplitz{T<:Number}(::Array{T<:Number,1}, ::Array{T<:Number,1}, ::Array{Complex{T<:Number},1}, ::Array{Complex{T<:Number},1}, ::Base.DFT.Plan{Complex{T<:Number}})
  ToeplitzMatrices.Toeplitz{T<:Number}(::Array{T<:Number,1}, ::Array{T<:Number,1})
  ToeplitzMatrices.Toeplitz{T1<:Number,T2<:Number}(::Array{T1<:Number,1}, ::Array{T2<:Number,1})
  ...
 in call at /home/kuan/Documents/git/ToeplitzMatrices.jl/src/ToeplitzMatrices.jl:120
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
while loading /home/kuan/Documents/git/test/test4.jl, in expression starting on line 32
```
The offending line is Line 120 in ToeplitzMatrices.jl, which calls the ctor but mismatches the type. 

I wonder the best way to fix this. Any ideas please?

**Comment by andreasnoack** [comment]
Things are a bit simpler if the matrices are either always real or always complex but we'll probably have to support both. My original application was statistics and data is typically real valued so I didn't consider complex matrices.

I almost have a patch ready in https://github.com/andreasnoack/ToeplitzMatrices.jl/tree/anj/complex where `Toeplitz`, `TriangularToeplitz` and `Circulant` support complex matrices. I've left out `Symmetric` for now since it should probably be `Hermitian`.

There is an issue, though. It appears that the CGS with Chan's preconditioner doesn't work well for complex matrices and I'm using the CGS for Toeplitz solves. It's been a while since I've read that literature so if you know anything about this it would be great if you could help.

**Comment by kuanxu** [comment]
@andreasnoack Thanks for the patch. I just scanned your commit and it looks pretty nice. I think it's sensible to leave out `Symmetric` for a well thought-out `Hermitian` to be in place.

I'm not a guru of iterative solvers. So, I don't have much to say about CGS. Do you think it is OK that we also leave out the support for complex solvers by throwing an error?

**Comment by andreasnoack** [comment]
I've found the issue. In several places, I converted to a real array with `real` after a fast multiplication or solve which is obviously only valid to do for real input. With that fixed, I think the solves work as well.

**Comment by kuanxu** [comment]
@andreasnoack That's a good news. Please go ahead. If possible, could you add a few more tests for the complex case? Probably you haven't looked much into the tests. Thanks.

**Comment by kuanxu** [comment]
@andreasnoack Is it still your plan to get https://github.com/andreasnoack/ToeplitzMatrices.jl/tree/anj/complex finished and merged?

**Comment by andreasnoack** [comment]
It is. Organizing JuliaCon + paper deadline came in the way.

**Comment by kuanxu** [comment]
@andreasnoack Thanks. I plan to do some benchmark to get a more justified breakeven for direct multiplication vs. fft, when the complex branch is merged.

**Comment by kuanxu** [comment]
It seems that a similar but different bug emerged recently and I have a hard time locating it. @andreasnoack Any recent development in dependencies may cause this error? 
 
```
ERROR: LoadError: MethodError: `convert` has no method matching convert(::Type{ToeplitzMatrices.Toeplitz{T<:Number}}, ::Array{Complex{Float64},1}, ::Array{Complex{Float64},1}, ::Array{Complex{Float64},1}, ::Array{Complex{Float64},1}, ::Base.DFT.FFTW.cFFTWPlan{Complex{Float64},-1,true,1})
This may have arisen from a call to the constructor ToeplitzMatrices.Toeplitz{T<:Number}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  ToeplitzMatrices.Toeplitz{T<:Number}(::Array{T<:Number,1}, ::Array{T<:Number,1}, ::Array{Complex{T<:Number},1}, ::Array{Complex{T<:Number},1}, ::Base.DFT.Plan{Complex{T<:Number}})
  ToeplitzMatrices.Toeplitz{T<:Number}(::Array{T<:Number,1}, ::Array{T<:Number,1})
  ToeplitzMatrices.Toeplitz{T1<:Number,T2<:Number}(::Array{T1<:Number,1}, ::Array{T2<:Number,1})
  ...
 in call at /home/kuan/.julia/v0.4/ToeplitzMatrices/src/ToeplitzMatrices.jl:111
 in anonymous at no file
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:320
while loading /home/kuan/Documents/git/ToeplitzMatrices.jl/test/runtests.jl, in expression starting on line 11
```

**Comment by kuanxu** [comment]
Sorry. My bad. The error is gone after rebooting the machine. Don't know what happened.
