### ISSUE TITLE
Load error on nightly

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaMatrices/ToeplitzMatrices.jl#25]
This is just a small head's up that there is a load error on nightly Julia builds. See, for example, https://travis-ci.org/MikaelSlevinsky/FastTransforms.jl/jobs/247697067.

I think it's because `FFTW` and `AbstractFFTs` are being moved out of Base? (Probably this means updating FastTransforms too!)

**Comment by dlfivefifty** [comment]
I'd recommend waiting a few months before trying to support nightly for the kinks to work out. (There's still a scattering of unnecessary `.+` in ApproxFun from when they briefly decided to deprecate `+(::Vector,::Vector)` in favour of `.+(::Vector,::Vector)` in 0.4pre.)

**Comment by andreasnoack** [comment]
This problem is fixed but there are many other problems. We'll have to wait a little longer before we can support 0.7 but I'll close here since there is nothing actionable for now.
