### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by rveltz** [JuliaMatrices/ToeplitzMatrices.jl#26]
Hi,

I am using your very cool package and I would like to make 2 suggestions.

Is it possible to make the following changes? 
- let the user pass the FFTW flag in the constructor
- use Blas operation in `A_mul_B!` to benefit from threading? For example at this [line](https://github.com/JuliaMatrices/ToeplitzMatrices.jl/blob/master/src/ToeplitzMatrices.jl#L71)

Thank you for your help,

Best regards

**Comment by andreasnoack** [comment]
> let the user pass the FFTW flag in the constructor

Could you explain in more detail what you are after here?

> use Blas operation in `A_mul_B!` to benefit from threading? For example at this line

It would probably be easy to use an `axpy!` here but have you been able to verify that threading will actually make a difference?

**Comment by rveltz** [comment]
Hi,

I was using your code for solving a differential equation (using convolutions) and I had to hack into your code to pass the flag FFTW.MEASURE. 

As for the second part, I will try your suggestion.

Thank you,

As for the second part, it really depends on the vector size

**Comment by andreasnoack** [comment]
Thanks for explaining. If you think your solution for passing the flag is useful beyond your application then a PR would be welcome. Regarding the threading, then my own experience is that it is difficult to get a speedup for functions that do so few flops per memory access.
