### ISSUE TITLE
Weird behavior of transposes and TriangularToeplitz

### ISSUE THREAD

**Issue by riccardosven** [JuliaMatrices/ToeplitzMatrices.jl#34]
Multiplying a vector by a lower triangular Toeplitz matrix gives weird results when associated with transposition:

```
g = [1.; 2.; 3.]
u = TriangularToeplitz([1.; 1.; 1.], :L)
```

then
```
g'*u
1×3 RowVector{Float64,Array{Float64,1}}:
 6.0  5.0  3.0
```
but
```
g'*u
1×3 RowVector{Float64,Array{Float64,1}}:
 3.0  2.0  0.0
```

Similarly
```
u.'*g
3-element Array{Float64,1}:
 3.0
 2.0
 0.0

u*g
3-element Array{Float64,1}:
 1.0
 3.0
 6.0
```

**Comment by andreasnoack** [comment]
Thanks for reporting. The methods here predates the `RowVector` so I'm not sure what this dispatches to. I'll take a look.

**Comment by rsrsl** [comment]
I've tried following the chain of calls, but I'm just a Julia beginner :)
I believe it is something in `A_mul_B!` as it also happens in conjunction to normal vector-matrix multiplication (not only with `RowVector`.

**Comment by dkarrasch** [comment]
I couldn't find an issue even with the currently released version, even more so since I don't understand where the issue should come from: two different results are reported for the exact same call `g'*u`. So I think this can be closed.
