### ISSUE TITLE
Make `Toeplitz` lightweight, add factorization/plan-like type for multiplication

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMatrices/ToeplitzMatrices.jl#36]
The current design of `Toeplitz` pre-plans for multiplication. This unfortunately limits the scope of this package to types that support FFTs. (For example, even `Int` is not supported!)

 I'd propose making `Toeplitz` itself lightweight, and allow a `plan` / `factorization` for pre-planned multiplication, something like:
```julia
T = planmul(Toeplitz([1.0,2,3], [1.0,2,3]))
```
would return a `PlannedToeplitz` that behaves like the current implementation.

One motivation: InfiniteArrays.jl. I want to be able to construct the semi-infinite discrete Laplacian by typing
```julia
Δ = Toeplitz([0; 1; Zeros(∞)],  [0; 1; Zeros(∞)])
```
Or the Infinite Hilbert matrix as
```julia
H = Hankel( (1:∞).^(-1))
```

**Comment by andreasnoack** [comment]
I think it would be fine to decouple the fft from the type a bit but I'd prefer a more hidden/automatic approach than using a `plan` function. I'm not sure how it would look like though.

**Comment by dlfivefifty** [comment]
One option would be to rename the current implementation as `PlannedToeplitz` and then `Toeplitz` becomes the lightweight version.

**Comment by dlfivefifty** [comment]
How do you feel about just using `factorize(::Toeplitz)`:
```julia
T = factorize(Toeplitz([1.0,2,3], [1.0,2,3]))
```
This would imply that `T isa Factorization`, not a `Matrix`, but I suspect this behaviour captures most use-cases of `Toeplitz`.

**Comment by andreasnoack** [comment]
I like the idea. It reflects the actual computation and people will expect some costs associated with a call to `factorize`.
