### ISSUE TITLE
Toeplitz matrix-vector multiply fails in 1.0.1

### ISSUE THREAD

**Issue by JeffFessler** [JuliaMatrices/ToeplitzMatrices.jl#40]
MWE:
```
using ToeplitzMatrices
Toeplitz([1, 2],[1, 2]) * ones(2)
```
fails with error message starting with:

ERROR: MethodError: no method matching
mul!(::Array{Float64,1},::Toeplitz{Float32,Complex{Float32}}, ::Array{Float64,1}, ::Float32, ::Float32)

followed by many long suggestions of alternative methods.

Same issue with Circulant.

pkg status:
  [c751599d] ToeplitzMatrices v0.4.2

**Comment by dlfivefifty** [comment]
Ah, it's a bug with integer entries. This works:
```julia
julia> Toeplitz([1.0, 2],[1, 2]) * ones(2)
2-element Array{Float64,1}:
 3.0
 3.0
```

**Comment by JeffFessler** [comment]
I see; I hadn't guessed that because the constructor makes it look like everything is Floats, but I suppose that internally it is more subtle:
```
A = Circulant(1:2)

2×2 Circulant{Float32,Complex{Float32}}:
 1.0  2.0
 2.0  1.0
```
Thanks for the work around.

**Comment by dlfivefifty** [comment]
We should allow integer-valued Toeplitz matrices anyways, which is one of the reasons to do https://github.com/JuliaMatrices/ToeplitzMatrices.jl/issues/36

**Comment by JeffFessler** [comment]
I've just hit this issue again, even without integers.  This simple command fails:

`Circulant(Float32.(1:3)) * ones(Float64, 3)`

ERROR: MethodError: no method matching mul!(::Array{Float64,1}, ::Circulant{Float32,Complex{Float32}}, ::Array{Float64,1}, ::Float32, ::Float32)

My hunch is that the issue is with the `T` in the 5-argument `mul!` here:
https://github.com/JuliaMatrices/ToeplitzMatrices.jl/blob/3a633b0a8bfd3ada898e48c4b0ae4f39584d983c/src/ToeplitzMatrices.jl#L45
I don't understand enough about how 5-arg `mul!` works overall to begin a PR on this...

I am using Julia 1.2 with ToeplitzMatrices v0.6.0

**Comment by jarlebring** [comment]
The function you are calling does not seem to support mixed precision. The code to extend the matrix and apply FFT in this function is not extremely complicated, so you may want to just check if it works for your case with a more general signature.

I would start by changing the signature to 
```
 function mul!(y::StridedVector, A::AbstractToeplitz, x::StridedVector, α::Number β::Number)
```
and see if the code just works for your case. 

The current signature seems quite restrictive IMHO. I don't see why one would force all the parameters to be the same number type. If they are not the same, there will be some type conversion, or error message.

**Comment by dlfivefifty** [comment]
Please make a PR to address this and it will be merged upon review
