### ISSUE TITLE
Tagging a new minor version for cholesky

### ISSUE THREAD

**Issue by willtebbutt** [JuliaMatrices/ToeplitzMatrices.jl#41]
Stheno.jl needs to depend on the `cholesky` factorisation functionality in this package. I would therefore greatly appreciate a new minor version being tagged as said functionality is currently only available on master.

**Comment by dlfivefifty** [comment]
Done: https://github.com/JuliaLang/METADATA.jl/pull/20407

I've also invited you to become a member of JuliaMatrices so you'll be able to tag releases.
