### ISSUE TITLE
Returned eltype of matrix is float32 when Int was expected

### ISSUE THREAD

**Issue by macd** [JuliaMatrices/ToeplitzMatrices.jl#44]
Using integer vectors to construct a Toeplitz matrix results in Float32 eltypes. Not at all what I was expecting.  I can of course do Toeplitz{Int}([1,2,3], [1,2,3]), but still...
```
julia v1.3> a = Toeplitz([1,2,3], [1,2,3])
3×3 Toeplitz{Float32,Complex{Float32}}:
 1.0  2.0  3.0
 2.0  1.0  2.0
 3.0  2.0  1.0

julia v1.3> eltype(a)
Float32
```

**Comment by dlfivefifty** [comment]
This is one of the motivations for https://github.com/JuliaMatrices/ToeplitzMatrices.jl/issues/36
